# Generated by Django 4.0.6 on 2022-07-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbnapi', '0002_generalstatistics_alter_birdnamedatabase_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdnamedatabase',
            options={'ordering': ['-bird_name']},
        ),
        migrations.AlterModelOptions(
            name='generalstatistics',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='requestrecord',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='scientificname',
            options={'ordering': ['-scientific_name']},
        ),
    ]
